### ISSUE TITLE
Make Gui for inputs

### ISSUE THREAD

**Issue by ashishkg0022** [ashishkg0022/gmail-attachments#6]
Use pyqt to make a gui , from which user can provide input

**Comment by parulc7** [comment]
I would like to work on this issue. Although I have not worked with PyQt, I have worked with tkinter a bit. Can you let me know how to get started?

**Comment by ashishkg0022** [comment]
@Deathrow77  first run the script and check its usability , accordingly you can add some gui stuff.

**Comment by parulc7** [comment]
Hey I have made a pull request for this issue under KWOC-2017. Please Check it out.[https://github.com/ashishkg0022/gmail-attachments/pull/8](url)

**Comment by rounakdatta** [comment]
Hi there, I've completed the GUI part using QtPy. Please have a look and review the code; https://github.com/ashishkg0022/gmail-attachments/pull/9

**Comment by ashishkg0022** [comment]
As both of you have opened a PR I will merge the better one. but thanks to both for the contribution.
